### ISSUE TITLE
Automate deployments

### ISSUE THREAD

**Issue by oed** [3box/3box-graphql#17]
When an update is pushed to **master**:
* Automatically deploy the serverless functions to `api.3box.io/graph/`

When an update is pushed to **develop**:
* Automatically deploy the serverless functions to `api-dev.3box.io/graph/`

**Comment by oed** [comment]
@c-castillo I'm pretty sure we did this right? If so we should close this.

**Comment by c-castillo** [comment]
Yes, closing this
