### ISSUE TITLE
Give the endpoint a recognizable name. 

### ISSUE THREAD

**Issue by zachferland** [3box/3box-graphql#6]
Maybe graphql.3box.io

**Comment by oed** [comment]
maybe graph.3box.io?

**Comment by michaelsena** [comment]
Need to agree on endpoint name first

**Comment by michaelsena** [comment]
https://api.3box.io/graph/

**Comment by oed** [comment]
@zachferland Do we have a story for using the new endpoints in the library?

**Comment by c-castillo** [comment]
IDK why the story did not close with the PR

**Comment by oed** [comment]
@c-castillo that didn't answer my question though!
